const express = require('express')
const authRoutes = require('./auth.routes')
const userRoutes = require('./user.routes')
const itemRoutes = require('./item.routes')
const supplierRoutes = require('./supplier.routes')
const uploadRoutes = require('./upload.routes')
const stockCountRoutes = require('./stockCount.routes')
const stockLevelRoutes = require('./stockLevel.routes')
const locationRoutes = require('./location.routes')
const wastageRoutes = require('./wastage.routes')
const purchaseRoutes = require('./purchase.routes')
const recipeRoutes = require('./recipe.routes')
const batchRoutes = require('./batch.routes')
const accountingGroupRoutes = require('./accountingGroup.routes')
const priceListRoutes = require('./priceList.routes')
const menuRoutes = require('./menu.routes')
const modifierGroupRoutes = require('./modifierGroup.routes')
const modifierRoutes = require('./modifier.routes')
const comboRoutes = require('./combo.routes')
const outletRoutes = require('./outlet.routes')
const taxProfileRoutes = require('./taxProfile.routes')
const deviceRoutes = require('./device.routes')
const productionCenterRoutes = require('./productionCenter.routes')
const customerRoutes = require('./customer.routes')
const roomTypeRoutes = require('./roomType.routes')
const roomRoutes = require('./room.routes')
const ratePlanRoutes = require('./ratePlan.routes')
const housekeepingTaskRoutes = require('./housekeepingTask.routes')
const staffRoutes = require('./staff.routes')
const clockRoutes = require('./clock.routes')
const salePeriodRoutes = require('./salePeriod.routes')
const posOrderRoutes = require('./posOrder.routes')
const drawerRoutes = require('./drawer.routes')

const router = express.Router()

router.get('/health', (req, res) => {
  res.json({ status: 'ok' })
})

router.use('/auth', authRoutes)
router.use('/users', userRoutes)
router.use('/items', itemRoutes)
router.use('/suppliers', supplierRoutes)
router.use('/uploads', uploadRoutes)
router.use('/stock-counts', stockCountRoutes)
router.use('/stock-levels', stockLevelRoutes)
router.use('/locations', locationRoutes)
router.use('/wastage', wastageRoutes)
router.use('/purchases', purchaseRoutes)
router.use('/recipes', recipeRoutes)
router.use('/batches', batchRoutes)
router.use('/accounting-groups', accountingGroupRoutes)
router.use('/price-lists', priceListRoutes)
router.use('/menus', menuRoutes)
router.use('/modifier-groups', modifierGroupRoutes)
router.use('/modifiers', modifierRoutes)
router.use('/combos', comboRoutes)
router.use('/outlets', outletRoutes)
router.use('/tax-profiles', taxProfileRoutes)
router.use('/devices', deviceRoutes)
router.use('/production-centers', productionCenterRoutes)
router.use('/customers', customerRoutes)
router.use('/room-types', roomTypeRoutes)
router.use('/rooms', roomRoutes)
router.use('/rate-plans', ratePlanRoutes)
router.use('/housekeeping-tasks', housekeepingTaskRoutes)
router.use('/staff', staffRoutes)
router.use('/clock', clockRoutes)
router.use('/sale-periods', salePeriodRoutes)
router.use('/pos-orders', posOrderRoutes)
router.use('/drawer', drawerRoutes)

module.exports = router
